<a href="https://colab.research.google.com/github/Pavansai0099/Machine-learning-code/blob/main/multiple_var_ml_lineare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('/content/home price multiple var.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [ ]:
import math
mediam=math.floor(df.bedroom.median())
mediam

3

In [ ]:
df.bedroom=df.bedroom.fillna(mediam)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [ ]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

383724.9999999998

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [ ]:
137.25*3000+-26025.*3+-6825. *40+383724.9999999998

444399.9999999998

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

example for the linear regrerssion


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
data = pd.read_csv('/content/multi ex 1.csv')
data

exprence  test  inter  salary
0       NaN   8.0      9   50000
1       NaN   8.0      6   45000
2       5.0   6.0      7   60000
3       2.0  10.0     10   65000
4       7.0   9.0      6   70000
5       3.0   7.0     10   62000
6      10.0   NaN      7   72000
7      11.0   7.0      8   80000

In [ ]:
import math
ms=math.floor(data.exprence.median())
ms

6

In [ ]:
data.exprence=data.exprence.fillna(ms)
data

exprence  test  inter  salary
0       6.0   8.0      9   50000
1       6.0   8.0      6   45000
2       5.0   6.0      7   60000
3       2.0  10.0     10   65000
4       7.0   9.0      6   70000
5       3.0   7.0     10   62000
6      10.0   NaN      7   72000
7      11.0   7.0      8   80000

In [ ]:
ns=math.floor(data.test.median())
ns


8

In [ ]:
data.test=data.test.fillna(ns)
data

exprence  test  inter  salary
0       6.0   8.0      9   50000
1       6.0   8.0      6   45000
2       5.0   6.0      7   60000
3       2.0  10.0     10   65000
4       7.0   9.0      6   70000
5       3.0   7.0     10   62000
6      10.0   8.0      7   72000
7      11.0   7.0      8   80000

In [ ]:
reg1 = linear_model.LinearRegression()
reg.fit(data[['exprence','test','inter']],data.salary)

LinearRegression()

In [ ]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [ ]:
reg.intercept_

11869.91869918695

In [ ]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47056.91056911])

In [ ]:
2813.00813008*2+1333.33333333*9+2926.82926829*6+11869.91869918695

47056.910569056956